.TH SAMPLE 1 UW
.\"
.\" sample.1
.\"
.\" Inspecting /software/local_cs-xh-admin.cs.private.uwaterloo.ca/man/man8
.\" 
.\"
.\" Maximal sections (union) appears to be (in apparent consistenct order)...
.\" .SH NAME
.\" .SH SYNOPSIS
.\" .SH WHERE
.\" .SH DESCRIPTION
.\" .SH OPTIONS
.\" .SH EXAMPLES
.\" .SH FILES
.\" .SH HOSTNAMES
.\" .SH SEE ALSO
.\" .SH NOTE
.\" .SH NOTES
.\" .SH BUGS
.\" 
.\" acc_query-graddb-ta-info.8 - seems to have maximal sections
.\" acc_startend_TA-cs.8 - seems to have maximal sections
.\"
.\" SYNOPSIS and WHERE and OPTIONS could use good examples
.\" I wonder if WHERE always comes between SYNOPSIS and DESCRIPTION ?
.\"
.SH NAME
sample \- just a for instance man page
.SH SYNOPSIS
.hc %
.B "%sample"
[fieldnumber]...
.SH DESCRIPTION

